apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-vyvo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-vyvo
    app.kubernetes.io/part-of: test-app-xyuw
  name: nodejs-no-dockerfile-vyvo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-vyvo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-vyvo
    spec:
      containers:
      - image: quay.io/susdas_quay_org/build-e2e-qfta-tenant/test-app-xyuw/nodejs-no-dockerfile-vyvo@sha256:b48eab04f6c39abb8bc46e9803e106408c2e4894c3a179a19d83af001052541d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
